# Base configs
baseurl: "https://robertotjesse.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Roberto Beth "
subtitle: "Family weekend"
author: "Roberto Beth"
header:
 title: "Photography"
 subtitle: "by Roberto beth "
footer:
 name: "Hey there, my name is Ram"
 bio: "I am a gis specialist and amatour photographer"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
 social_urls:
   instagram: "https://www.instagram.com/ram_patra"
   dribbble: "https://dribbble.com/rampatra"
   linkedin: "https://in.linkedin.com/in/ram-patra"
   github: "https://www.github.com/rampatra"
